### ISSUE TITLE
Can't find source code for DeeplabV3+ training

### ISSUE THREAD

**Issue by chekhovana** [beric7/structural_inspection_main#1]
Where can I find source code for training DeeplabV3+ on corrosion segmentation task? When I am trying to load provided weights:

`state_dict = torch.load('l2_loss/weights_35.pt')`

I got the following error:

`ModuleNotFoundError: No module named 'network'`

**Comment by beric7** [comment]
Hi,

Thanks for the question. The error you are receiving is because you do not
have the 'network' folder in the same level as wherever you are loading the
weights. If you are in the Visualization Folder, your file system should
look like this.
![image (3)](https://user-images.githubusercontent.com/18520671/149995676-5b3009a0-444f-4cfa-8731-95381200c5e5.png)

And you try loading the weights in 'run_show_results.py'. It should work
this way. Please let me know if it does not or send me a screenshot of your
file system folder.

I also recommend that you clone the repository if you have not done so
already, before proceeding.

I hope this helps, and if it does not please do not hesitate to let me know.

**Comment by chekhovana** [comment]
Hi,

thanks a lot, I found it.
